### ISSUE TITLE
nlp.spot not returning entity array, but rather an object

### ISSUE THREAD

**Issue by Kroid** [spencermountain/nlp_compromise#21]
From https://github.com/Kroid/angular-nlp-compromise/issues/1 :

```
nlp.spot("joe carter loves toronto");
``` 
![screen](https://cloud.githubusercontent.com/assets/882236/6337139/bf0845f4-bb75-11e4-8c17-e82af1e38323.png)

From docs:

```
nlp.spot("joe carter loves toronto")
// ["joe carter", "toronto"]
```

I checked it from chrome console in example page http://rawgit.com/spencermountain/nlp_compromise/master/client_side/cute_demo/index.html

**Comment by spencermountain** [comment]
yeah, that's just lazy documentation. i'm planning on doing a lot of work on this library in two weeks, and things will change. i'll fix this then, and let you know about any breaking changes.

**Comment by lilnate22** [comment]
so is thew example doc wrong? or the code base?

**Comment by spencermountain** [comment]
fixed. thanks you two

**Comment by lilnate22** [comment]
not fixed:

![image](https://cloud.githubusercontent.com/assets/882236/7204536/154db2d8-e4f1-11e4-9695-270a16a6662d.png)
